version: "3.9"

services:
  mlflow:
    image: python:3.11-slim
    container_name: fraud_mlflow
    working_dir: /app
    volumes:
      - ./mlflow:/app/mlruns
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install mlflow --quiet &&
               mlflow server
               --host 0.0.0.0
               --port 5000
               --backend-store-uri /app/mlruns
               --default-artifact-root /app/mlruns"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: fraud_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./src/api:/app/src/api

networks:
  default:
    name: fraud_network